version: '3.8'

services:
  postgres:
    container_name: postgres-api-reservation
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_reservation
    volumes:
      - ./data/postgres:/var/lib/postgresql/data